version: "3.5"

services:

rrdrest:
    #image: michaelwadman/rrdrest:latest
    image: ansonlin/monitoring:librenms-rrdrest
    container_name: rrdrest
    restart: always
    volumes:
    - "./librenms:/opt/librenms"
    environment:
    - TZ=Asia/Taipei
    ports:
    - "9000:9000"
